project:
  type: book
  output-dir: docs
   
book:
  title: "Human Geography"
  author: "Moinul Islam"
  search: true
  # repo-url: https://github.com/moineco
  # downloads: [epub]
  date: today
  chapters:
    - index.qmd
    - syllabus.qmd
    - lecture_1.qmd
    - lecture_2.qmd
    - lecture_3.qmd
    - lecture_4.qmd
    - lecture_5.qmd
    - lecture_6.qmd
    - lecture_7.qmd
    - lecture_8.qmd
    - lecture_9.qmd
    - lecture_10.qmd
    - lecture_11.qmd
    - lecture_12.qmd
    - lecture_13.qmd
    - lecture_14.qmd
    - lecture_15.qmd
    - annex_1.qmd
    - references.qmd

bibliography: human_geography.bib
highlight-style: pygments

format:
  html:
    theme: 
       light: cosmo
       dark: darkly
    prefer-html: true
  # epub:
  # cover-image: cover.png
editor: visual

