# Packages for GIS

-   **R** is one of the most widely used programming languages nowadays, along with Python, especially in geographic and satellite data science.

-   **RStudio** is probably the most popular Integrated Development Environment (IDE) for **R**. When using RStudio, the **R** interpreter is hidden in the back-end, and **RStudio** is the front-end application that allows you to interact with the interpreter.

-   **R** is maintained by an international team of developers who make the language available through the web page of [R](https://cran.r-project.org).

-   Download [RStudio](https://posit.co/downloads/) from this link. Just click the "Download RStudio" button and follow the simple instructions.

-   We will represent the packages by using {}.

## **R** packages for management:

1.  **{devtools}**

-   CRAN: install.packages("devtools")
-   GitHub: devtools::install_github("r-lib/devtools")

2.  **{remotes}**

-   CRAN: install.packages("remotes")
-   GitHub: remotes::install_github("r-lib/conflicted")

3.  **{pak}**

-   CRAN: install.packages("pak")

4.  **{pacman}**

-   CRAN: install.packages("pacman")
-   GitHub: devtools::install_github("r-lib/devtools")

5.  **{stargazer}**

-   CRAN: install.packages( "stargazer")
-   GitHub: devtools::install_github("ChandlerLutz/stargazer")

6.  **{readxl}**

-   CRAN: install.packages("readxl")
-   GitHub: remotes::install_github("hadley/readxl")

7.  **{here}**

-   CRAN: install.packages("here")
-   GitHub: devtools::install_github("r-lib/here")

8.  **{rvest}**

-   CRAN: install.packages("rvest")
-   GitHub: devtools::install_github("tidyverse/rvest")

9.  **{cowplot}**

-   CRAN: install.packages("cowplot")
-   GitHub: remotes::install_github("wilkelab/cowplot")

10. **{ggthemes}**

-   CRAN: install.packages('ggthemes', dependencies = TRUE)
-   GitHub: devtools::install_github(c("hadley/ggplot2", "jrnold/ggthemes"))

11. **{ggpubr}**

-   CRAN: install.packages("ggpubr")
-   GitHub: devtools::install_github("kassambara/ggpubr")

12. **{plotly}**

-   CRAN: install.packages("plotly")
-   GitHub: devtools::install_github("ropensci/plotly")

13. **{stringr}**

-   CRAN: install.packages("stringr")
-   GitHub: devtools::install_github("hadley/stringr")

14. **{patchwork}**

-   CRAN: install.packages("patchwork")
-   GitHub: devtools::install_github("thomasp85/patchwork")

15. **{magrittr}**

-   CRAN: install.packages("magrittr")
-   GitHub: devtools::install_github("tidyverse/magrittr")

16. **{DBI}** \[Connect R to database management systems\]

-   CRAN: install.packages("DBI")
-   GitHub: devtools::install_github("rstats-db/DBI")

17. **{RSQLite}** \[Easy way to use a database from R because the package itself contains SQLite\]

-   CRAN: install.packages("RSQLite")
-   GitHub: devtools::install_github("r-dbi/RSQLite")

18. **{DT}** \[Extension of dataframe for fast processing of large data\]

-   CRAN: \`install.packages("DT")

19. **{lubridate}** \[Functions to work with date-times and time-spans\]

-   CRAN: install.packages("lubridate")
-   GitHub: devtools::install_github("tidyverse/lubridate")

## **R** packages for GIS:

### Basic data manipulation

1.  **{sf}** \[for vector data\]

-   CRAN: install.packages("sf")
-   GitHub: remotes::install_github("r-spatial/sf")

**sf** package installation in Windows OS is straight frward. And the above codes should be sufficient to install {sf}. However, in MacOS and Linux (Ubuntu/Fedora), some additional steps are necessary.

-   For MacOS

-- First we need to install {gdal} and the easiest way to install {gdal} is using Homebrew.

```
brew install pkg-config
brew install gdal
```

-- Next we need to install {sf} by using following command.

```
install.packages("sf", type = "source", configure.args = "--with-proj-lib=$(brew --prefix)/lib/")
```

2.  **{raster}** \[for raster data\]

-   CRAN: install.packages("raster")
-   GitHub: remotes::install_github("rspatial/raster")

3.  **{shapefiles}**

-   CRAN: install.packages("shapefiles")

4.  **{ncdf4}**

-   CRAN: install.packages(“ncdf4”)
-   GitHub: devtools::install_github("mdsumner/ncdf4")

5.  **{sp}**

-   CRAN: install.packages("sp", dependencies=TRUE)
-   GitHub: devtools::install_github("edzer/sp")

### Cartography and data visualization

1.  **{tidyverse}** \[Includes the packages {ggplot2}, {dplyr}, {tidyr}, {readr}, {purrr}, {tibble}, {stringr}, {forcats}\]

-   CRAN: install.packages("tidyverse")
-   GitHub: pak::pak("tidyverse/tidyverse")

2.  **{RColorBrewer}**

-   CRAN: install.packages("RColorBrewer")
-   GitHub: devtools::install_github("cran/RColorBrewer")

3.  **{viridis}**

-   CRAN: install.packages("viridis")
-   GitHub: devtools::install_github("sjmgarnier/viridis")

4.  **{tmap}**

-   CRAN: install.packages("tmap")
-   GitHub: pak::pak("r-tmap/tmap")

5.  **{leaflet}**

-   CRAN: install.packages("leaflet")
-   GitHub: devtools::install_github("rstudio/leaflet")

6.  **{mapview}**

-   CRAN: install.packages("mapview")
-   GitHub: remotes::install_github("r-spatial/mapview")

7.  **{cartography}**

-   CRAN: install.packages("cartography")
-   GitHub: remotes::install_github("riatelab/cartography")

8.  **{ggmap}**

-   CRAN: install.packages("ggmap")
-   GitHub: remotes::install_github("dkahle/ggmap")

9.  **{rayshader}**

-   CRAN: install.packages("rayshader")
-   GitHub: devtools::install_github("tylermorganwall/rayshader")

10. **{geojsonio}**

-   CRAN: install.packages("geojsonio")
-   GitHub: devtools::install_github("ropensci/geojsonio")

11. **{shinyjs}**

-   CRAN: install.packages("shinyjs")
-   GitHub: remotes::install_github("daattali/shinyjs")

12. **{GGally}** \[Extends {ggplot2} by adding several functions to reduce the complexity of combining geometric objects with transformed data\]

-   CRAN: install.packages("GGally")
-   GitHub: devtools::install_github("ggobi/ggally")

13. **{grid}** \[A set of graphical functions which support a great deal of flexibility in the layout of graphics\]

-   CRAN: install.packages("grid")
-   GitHub: devtools::install_github("cran/grid")

14. **{gridExtra}** \[Provides a number of user-level functions to work with "grid" graphics, notably to arrange multiple grid-based plots on a page, and draw tables\]

-   CRAN: install.packages("gridExtra")
-   GitHub: devtools::install_github("cran/gridExtra")

15. **{cartogram}** \[Construct continuous and non-contiguous area cartograms\]

-   CRAN: install.packages("cartogram")
-   GitHub: devtools::install_github("sjewo/cartogram")

16. **{visNetwork}** \[Use vis.js library for network visualization\]

-   CRAN: install.packages("visNetwork")
-   GitHub: devtools::install_github("datastorm-open/visNetwork")

### Spatial statistics

1.  **{spatial}**

-   GitHub: remotes::install_github("rspatial/rspatial")

2.  **{spatstat}**

-   CRAN: install.packages("spatstat")
-   GitHub: remotes::install_github("spatstat/spatstat")

3.  **{gstat}**

-   CRAN: install.packages("gstat")
-   GitHub: remotes::install_github("r-spatial/gstat")

4.  **{spdep}**

-   CRAN: install.packages("spdep", repos="http://R-Forge.R-project.org")
-   GitHub: devtools::install_github("r-spatial/spdep")

5.  **{geoshape}**

6.  **{ggspatial}**

-   CRAN: install.packages("ggspatial")
-   GitHub: remotes::install_github("paleolimbot/ggspatial")

7.  **{spdep}** \[A collection of functions to create spatial weights matrix objects from polygon\]

-   CRAN: install.packages("spdep")
-   GitHub: devtools::install_github("r-spatial/spdep")

8.  **{geogrid}** \[Turn geospatial polygons into regular or hexagonal grids\]

-   GitHub: devtools::install_github("jbaileyh/geogrid")

9.  **{GISTools}** \[Some further GIS capabilities for R\]

-   CRAN: install.packages("GISTools")

10. **{RgoogleMaps}**

-   CRAN: install.packages("RgoogleMaps")
-   GitHub: devtools::install_github("cran/RgoogleMaps")

### Data sources

1.  **{OpenStreetMap}**

-   CRAN: install.packages("OpenStreetMap")
-   GitHub: devtools::install_github("cran/OpenStreetMap")

2.  **{rnaturalearth}**

-   CRAN: install.packages("rnaturalearth", dependencies = TRUE)
-   GitHub: devtools::install_github("ropensci/rnaturalearth")

3.  **{rnaturalearthdata}**

-   CRAN: install.packages("rnaturalearthdata")
-   GitHub: devtools::install_github("ropensci/rnaturalearthdata")

4.  **{rastervis}**

-   CRAN: install.packages("rasterVis")
-   GitHub: devtools::install_github("oscarperpinan/rasterVis")

5.  **{maps}**

-   CRAN: install.packages("maps")

6.  **{spData}**

-   CRAN: install.packages("spData")
-   GitHub: devtools::install_github("nowosad/spData")

7.  **{rgeos}**

-   CRAN: install.packages("rgeos", repos="http://R-Forge.R-project.org")
-   GitHub: devtools::install_github("cran/rgeos")

8.  **{jpndistrict}**

-   CRAN: install.packages("jpndistrict")
-   GitHub: devtools::install_github("uribo/jpndistrict", force=TRUE)

9.  **{countrycode}**

-   CRAN: install.packages("countrycode")
-   GitHub: install_github('vincentarelbundock/countrycode')

10. **{tmaptools}**

-   CRAN: install.packages("tmaptools")
-   GitHub: devtools::install_github("mtennekes/tmaptools")

11. **`DT`**

-   CRAN: install.packages("DT")
-   GitHub: remotes::install_github("rstudio/DT")

12. **{usmap}**

-   CRAN: install.packages("usmap")
-   GitHub: devtools::install_github("pdil/usmap")

13. **{tigris}**

-   CRAN: install.packages("tigris")
-   GitHub: devtools::install_github("walkerke/tigris")

14. **{scales}**

-   CRAN: install.packages("scales")
-   GitHub: devtools::install_github("r-lib/scales")

15. **{ggrepel}**

-   CRAN: install.packages("ggrepel")
-   GitHub: devtools::install_github("slowkow/ggrepel")

16. **{tidycensus}**

-   CRAN: install.packages("tidycensus")
-   GitHub: remotes::install_github("walkerke/tidycensus")
